project:
  type: website
  output-dir: docs
  resources:
    - assets/cv.pdf

website:
  title: "Denis Patterson"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: people.qmd
        text: Projects & Students
    right:
      - icon: envelope
        href: mailto:denis.d.patterson@durham.ac.uk
        aria-label: Email
  google-analytics: "G-P1970XP1S5"
  page-footer:
    left: "© Denis Patterson"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, custom.scss]
    toc: false
    link-external-newwindow: true
    title-block-banner: "#1e2d3d"
    title-block-banner-color: "#ffffff"
